import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // SDK is built with tsup — both CJS and ESM outputs land in dist/.
    // Don't lint generated bundles; source under packages/sdk/src is the truth.
    "packages/*/dist/**",
    // Anchor build artifacts (generated IDL + TS types, regenerated by `anchor build`).
    "target/**",
    // One-off scratch file at repo root.
    "test-program.js",
  ]),
]);

export default eslintConfig;
